[package]
name = "cargo-wapm"
version = "0.1.0"
authors = ["Hammer of the Gods <developers@hotg.ai>"]
license = "Apache-2.0"
edition = "2021"
description = "A CLI tool for publishing Rust crates to WAPM."

[dependencies]
anyhow = "1.0.57"
cargo_metadata = "0.14.2"
clap = { version = "3.1.15", features = ["derive", "env"] }
serde = "1.0.137"
toml = "0.5.9"
tracing = { version = "0.1.34", features = ["attributes"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[workspace]
members = [".", "examples/hello-world"]

[profile.release]
strip = "debuginfo"
